#
# Copyright (c) 2025 ZettaScale Technology
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
#
# Contributors:
#   ZettaScale Zenoh Team, <zenoh@zettascale.tech>
#
name: qnx710

on:
  workflow_call:

jobs:
  build:
    name: Build on ${{ matrix.os }} for ${{ matrix.arch }} with shared=${{ matrix.shared }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubu22-qnx]
        arch: ["x86_64", "aarch64le"]
        shared: [1, 0]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          source ~/qnx710/qnxsdp-env.sh
          Z_FEATURE_UNSTABLE_API=1 \
          Z_FEATURE_ADVANCED_PUBLICATION=1 \
          Z_FEATURE_ADVANCED_SUBSCRIPTION=1 \
          make CMAKE_TOOLCHAIN_FILE=${PWD}/ports/qnx/qnx-sdp710-${ARCH}.cmake
        env:
          ARCH: ${{ matrix.arch}}
          BUILD_SHARED_LIBS: ${{ matrix.shared }}
